GET http://localhost:8080/user/search?query=keraunos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF0cmV1cy5zZXJ2aWNlQHZvbGtzd2FnZW4uZGUiLCJleHAiOjE3Mzc2NTEwNjAsInVzZXJJZCI6IjE3ZDQxODVlLTE0ZjctNGM1OS1hNzhkLThmYmViNDBhNTk1ZSJ9.r2_0rlpZWhig16izrhtasNNA4Qdb6oZwJY_pnkICqzc